contacts = [
    {
        id: 'c1',
        name: 'Momin Raza',
        address: 'Shishgarh',
        work: 1,
        number: 7302606166,
    },
    {
        id: 'c2',
        name: 'Abhishek',
        address: 'Shishgarh',
        work: 2,
        number: 7302606166,
    },
    {
        id: 'c3',
        name: 'Najim',
        address: 'Shishgarh',
        work: 3,
        number: 7302606166,
    },
    {
        id: 'c4',
        name: 'saif',
        address: 'Shishgarh',
        work: 4,
        number: 7302606166,
    },
    {
        id: 'c5',
        name: 'Mo Islam',
        address: 'Shishgarh',
        work: 5,
        number: 7302606166,
    },
    {
        id: 'c6',
        name: 'Zaid Raza',
        address: 'Shishgarh',
        work: 5,
        number: 7302606166,
    },
    {
        id: 'c7',
        name: 'Uzam Raza',
        address: 'Shishgarh',
        work: 5,
        number: 7302606166,
    },
    {
        id: 'c8',
        name: 'Mo Hammad',
        address: 'Shishgarh',
        work: 5,
        number: 7302606166,
    },
];